---
title: "Rkode"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##  Polynommultiplikation
```{r}
polymult <- function(x,a,b)
  # a(B) = a_0 + a_1*B + a_2*B² + ... + a_p*B^p
  # b(B) = b_0 + b_1*B + b_2*B² + ... + a_q*B^q
  # where wlog p >= q
  # Result is a(B)b(B) x_t
{
  if (length(b) == 1){polycoeff <- b[1]*array(a)}
  else
  {alpha <- array(a)
  p <- dim(alpha) - 1
  beta <- array(b)
  q <- dim(beta) - 1
  # Assumed: p >= q
  polycoeff <- array(rep(0,p+q + 1))
  for (k in 0:(p+q))
    for (j in max(0,k-q):min(k,p))
    {polycoeff[k+1] <- polycoeff[k+1] + alpha[j+1]*beta[k-j+1]}
  }
  return(filter(x,c(polycoeff),sides=1, method="convolution"))
  # test: return(polycoeff)
}

```
## Opstilling af Data
```{r}
library(readxl)
library(vars)
library(imputeTS)
library(forecast)
library(tseries)
library(stats)
library(strucchange)
library(tidyr)
library(astsa)
elprice17 =  data.frame(read.csv("elspot-prices_2017_daily_eur.csv",sep=";",dec=","))

cons17= data.frame(read.csv("consumption-se-areas_2017_daily.csv",sep=";"))

prod17 = data.frame(read.csv("production-se-areas_2017_daily.csv",sep=";"))


Price = log(na_interpolation(as.numeric(elprice17[3:367,4]), option = "linear"))

Cons = log(na_interpolation(as.numeric(as.character(cons17[3:367,3])), option = "linear"))

Prod = log(na_interpolation(as.numeric(as.character(prod17[3:367,3])), option = "linear"))


plot.ts(Price)

plot.ts(Cons)

plot.ts(Prod)

acf(Price)

acf(Cons)

acf(Prod)



dato <- seq(c(ISOdate(2017,1,1)), by = "days", length.out = 365)

data1 = data.frame(dato, Price, Cons, Prod)

Prod1= data1[,c(1,4)]

Cons1 = data1[,c(1,3)]

Price1 = data1[,c(1,2)]
```

## Estimation af deterministisk sæson 
```{r}
sprod = glm(Prod1[,2] ~ time(Prod1[,1]) + 
                    I(time(Prod1[,1])^2) +
                    sin((4*pi)/365*I(time(Prod1[,1])))+ 
                    cos((4*pi)/365*I(time(Prod1[,1])))+  
                    sin((8*pi)/365*I(time(Prod1[,1])))+ 
                    cos((8*pi)/365*I(time(Prod1[,1])))+
                    sin((24*pi)/365*I(time(Prod1[,1])))+ 
                    cos((24*pi)/365*I(time(Prod1[,1])))+
                    sin((104*pi)/365*I(time(Prod1[,1])))+ 
                    cos((104*pi)/365*I(time(Prod1[,1])))+
                    sin((730*pi)/365*I(time(Prod1[,1])))+ 
                    cos((730*pi)/365*I(time(Prod1[,1])))
)

sprice = glm(Price1[,2] ~ time(Price1[,1]) + 
              I(time(Price1[,1])^2) +
              sin((4*pi)/365*I(time(Price1[,1])))+ 
              cos((4*pi)/365*I(time(Price1[,1])))+  
              sin((8*pi)/365*I(time(Price1[,1])))+ 
              cos((8*pi)/365*I(time(Price1[,1])))+
              sin((24*pi)/365*I(time(Price1[,1])))+ 
              cos((24*pi)/365*I(time(Price1[,1])))+
              sin((104*pi)/365*I(time(Price1[,1])))+ 
              cos((104*pi)/365*I(time(Price1[,1])))+
              sin((730*pi)/365*I(time(Price1[,1])))+ 
              cos((730*pi)/365*I(time(Price1[,1])))
)


scons = glm(Cons1[,2] ~ time(Cons1[,1]) + 
              I(time(Cons1[,1])^2) +
              sin((4*pi)/365*I(time(Cons1[,1])))+ 
              cos((4*pi)/365*I(time(Cons1[,1])))+  
              sin((8*pi)/365*I(time(Cons1[,1])))+ 
              cos((8*pi)/365*I(time(Cons1[,1])))+
              sin((24*pi)/365*I(time(Cons1[,1])))+ 
              cos((24*pi)/365*I(time(Cons1[,1])))+
              sin((104*pi)/365*I(time(Cons1[,1])))+ 
              cos((104*pi)/365*I(time(Cons1[,1])))+
              sin((730*pi)/365*I(time(Cons1[,1])))+ 
              cos((730*pi)/365*I(time(Cons1[,1])))
)

summary(sprod)
summary(scons)
summary(sprice)

sprod_res = as.ts(sprod$residuals)
sprice_res = as.ts(sprice$residuals)
scons_res = as.ts(scons$residuals)

acf2(sprod_res)
acf2(sprice_res)
acf2(scons_res)



```

# Estimation og valg af SARMA for Pris
```{r}
acf2(sprice_res)

seas_sprice_res1 = sarima(sprice_res,3,0,0,1,0,0,7, no.constant = TRUE);



seas_sprice_res2 = sarima(sprice_res,2,0,0,1,0,0,7, no.constant = TRUE);



seas_sprice_res3 = sarima(sprice_res,4,0,0,1,0,0,7, no.constant = TRUE);



seas_sprice_res4 = sarima(sprice_res,3,0,0,2,0,0,7, no.constant = TRUE);



seas_sprice_res5 = sarima(sprice_res,3,0,0,0,0,0,7, no.constant = TRUE);

seas_sprice_res1$AIC

seas_sprice_res2$AIC

seas_sprice_res3$AIC

seas_sprice_res4$AIC

seas_sprice_res5$AIC

```

# Estimation og valg af SARMA for Forbrug

```{r}
seas_scons_res1 = sarima(scons_res,1,0,0,1,0,0,7, no.constant = TRUE)



seas_scons_res2 = sarima(scons_res,2,0,0,1,0,0,7, no.constant = TRUE)



seas_scons_res3 = sarima(scons_res,1,0,0,2,0,0,7, no.constant = TRUE)



seas_scons_res4 = sarima(scons_res,1,0,0,0,0,0,7, no.constant = TRUE)


seas_scons_res1$AIC
seas_scons_res2$AIC 
seas_scons_res3$AIC 
seas_scons_res4$AIC 


```

# Estimation og valg af SARMA for Produktion
```{r}

seas_sprod_res1 = sarima(sprod_res,1,0,0,2,0,0,7, no.constant = TRUE)



seas_sprod_res2 = sarima(sprod_res,2,0,0,2,0,0,7, no.constant = TRUE)



seas_sprod_res3 = sarima(sprod_res,3,0,0,2,0,0,7, no.constant = TRUE)



seas_sprod_res4 = sarima(sprod_res,0,0,0,2,0,0,7, no.constant = TRUE)



seas_sprod_res5 = sarima(sprod_res,1,0,0,1,0,0,7, no.constant = TRUE)



seas_sprod_res6 = sarima(sprod_res,1,0,0,0,0,0,7, no.constant = TRUE)


seas_sprod_res7 = sarima(sprod_res,1,0,0,3,0,0,7, no.constant = TRUE)



seas_sprod_res1$AIC

seas_sprod_res2$AIC

seas_sprod_res3$AIC

seas_sprod_res4$AIC

seas_sprod_res5$AIC

seas_sprod_res6$AIC

seas_sprod_res7$AIC



```

#SARMA
```{r}
seas_y1res = ts(seas_sprice_res1$fit$residuals)
coefs_y1 = seas_sprice_res1$fit$coef

coefs_season_Phi_y1 = c(1,rep(0,6),-coefs_y1[2])

stat_y1 = polymult(sprice_res,coefs_season_Phi_y1,1)


seas_x1res = ts(seas_sprod_res3$fit$residuals)
coefs_x1 = seas_sprod_res3$fit$coef

coefs_season_Phi_x1 = c(1,rep(0,6),-coefs_x1[2])

stat_x1 = polymult(sprod_res,coefs_season_Phi_x1,1)


seas_z1res = ts(seas_scons_res3$fit$residuals)
coefs_z1 = seas_scons_res3$fit$coef

coefs_season_Phi_z1 = c(1,rep(0,6),-coefs_z1[2])

stat_z1 = polymult(scons_res,coefs_season_Phi_z1,1)


```


## Opstilling af VAR-model
```{r}

XXX = data.frame(stat_z1,stat_x1,stat_y1)[8:365,]

var_xx = VAR(XXX, lag.max = 8)

VARselect(XXX)

summary(var_xx)

var = restrict(var_xx)

summary(var)


```
#Test af residualerne

```{r}
roots(var)

serial.test(var, type = "BG")

arch.test(var)

normality.test(var)

```




#Impulse Response Funktioner
```{r}
irf = irf(var, ortho = TRUE)
plot(irf)

```

#Opstilling af SVAR
```{r}
amat = diag(3)
diag(amat) = 1
amat[2,1] = NA
amat[3,1] = NA
amat[3,2] = NA

amat

svar = SVAR(var, Amat= amat, estmethod = "direct")

summary(svar)
```

